spring:
  redis:
    host: redis-11249.c301.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 11249
    password: CRsVdToVPbajb1xljjoCOhXqUzRYJ1om
  data:
    mongodb:
      uri: mongodb+srv://umairsheikh1991:b4VYnnT3%40DE6iB5@springboot.hrlnepl.mongodb.net/?retryWrites=true&w=majority&appName=SpringBoot
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: muhammad.umair@jeeny.me
    password: znxz hykm ffhp xmon
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

